application: cdit-dashboard
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|csv))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|csv))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
